### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by tasleson** [cholcombe973/blkid#2]
A couple of general questions.

1.  When building a simple executable which uses `blkid` is see:

```
   Compiling bitflags v0.9.1
   Compiling unicode-xid v0.0.4
   Compiling bitflags v0.8.2
   Compiling rustc-serialize v0.3.24
   Compiling strsim v0.7.0
   Compiling glob v0.2.11
   Compiling unicode-width v0.1.4
   Compiling libloading v0.4.3
   Compiling vec_map v0.8.0
   Compiling term v0.4.6
   Compiling regex v0.2.10
   Compiling cfg-if v0.1.2
   Compiling peeking_take_while v0.1.2
   Compiling ucd-util v0.1.1
   Compiling bitflags v1.0.1
   Compiling ansi_term v0.11.0
   Compiling lazy_static v0.2.11
   Compiling libc v0.2.39
   Compiling utf8-ranges v1.0.0
   Compiling void v1.0.2
   Compiling textwrap v0.9.0
   Compiling log v0.4.1
   Compiling clang-sys v0.19.0
   Compiling regex-syntax v0.5.3
   Compiling unreachable v1.0.0
   Compiling log v0.3.9
   Compiling thread_local v0.3.5
   Compiling atty v0.2.8
   Compiling memchr v1.0.2
   Compiling errno v0.2.3
   Compiling memchr v2.0.1
   Compiling clap v2.31.2
   Compiling nom v3.2.1
   Compiling aho-corasick v0.6.4
   Compiling syntex_pos v0.58.1
   Compiling syntex_errors v0.58.1
   Compiling cexpr v0.2.3
   Compiling syntex_syntax v0.58.1
   Compiling env_logger v0.4.3
   Compiling aster v0.41.0
   Compiling quasi v0.32.0
   Compiling syntex v0.58.1
   Compiling quasi_codegen v0.32.0
   Compiling bindgen v0.26.3
   Compiling blkid-sys v0.1.2
   Compiling blkid v0.2.0
```
This seems like a lot of library dependencies.  I've written one rust FFI for sdjournal and it's only dependency is `libc` [ref.](https://github.com/tasleson/sdjournal), is all this really needed or just an artifact of bindgen?

2. The generated constants for flags are declared as  things like:
```rust
pub const BLKID_SUBLKS_USAGE: c_uint = 128
```
Even though in usage the `flags` parameter is `c_int`, thus necessitating a cast.   The C header defines the value as:
```C
#define BLKID_SUBLKS_USAGE      (1 << 7) /* define USAGE result value */
```
which may be complicating things.  Can this be configured to auto generate the correct type?

**Comment by cholcombe973** [comment]
1. Yeah so if you look at the Cargo.toml in my library it depends on a few things.  libc, errno and blkid-sys.  blkid-sys just depends on bindgen.  If you look at the Cargo.lock file after you build you can see the dependency tree.  it looks like the vast majority of these packages are being pulled in from bindgen.  I agree it's a lot but there's not really a way to get around this that I know of.  Do you have space concerns or something?  

2. It's possible that because I generated these files awhile ago on an older version of bindgen that it was doing something that wasn't correct.  blkid-sys uses bindgen 0.26 and the current version is 0.33.  I'd try just changing the value in the blk-sys Cargo.toml, rerunning the build and seeing what the output from bindgen is.  It's possible in a newer version that they do a more correct conversion.  Hard to say without running it.

**Comment by tasleson** [comment]
Most of the stuff getting compiled is to build bindgen, has nothing to do with resultant binary.  Also, even though the bindings are slightly different between different versions of bindgen, it does appear to compile without issues.  Closing.
